### ISSUE TITLE
How to prevent two bluetooth connections?

### ISSUE THREAD

**Issue by pvanthony** [fdanis-oss/pw_wp_bluetooth_rpi_speaker#2]
Just installed using 2022-09-22 image and followed the instructions. All works as per the blog.

While playing the song through bluetooth from my mobile phone, my friend came and paired to the same unit and started playing his song. Now both songs can be heard.

Is there a way to prevent the new paired device from playing a song? Until the first paired device stop playing the song. Then the second paired device can play the song.

I hope I am clear in my explanation.

I am hoping to use the gpio pins to connect a toggle switch to kick the first person out and allow the second person to play his song.

**Comment by pvanthony** [comment]
Received the following reply in the blog.

Yes, nothing prevents multiple A2DP connections and PipeWire will mix the audio.

One way to prevent this should be to reject the connection to the A2DP service (AuthorizeService method in [speaker-agent.py](https://www.collabora.com/speaker-agent.py)) if another device is already connected, and keep track of the connected device.

**Comment by pvanthony** [comment]
From what I understand, the change has to be done in the following section, correct?
`    def AuthorizeService(self, device, uuid):
        # Always authorize A2DP and AVRCP connection
        if uuid in [A2DP, AVRCP]:
            print("AuthorizeService (%s, %s)" % (device, uuid))
            return
        else:
            print("Service rejected (%s, %s)" % (device, uuid))
        raise Rejected("Connection rejected by user")`

**Comment by fdanis-oss** [comment]
@pvanthony Sorry for the late reply

I created a pull request #5 to add an option which prevent multiple device connections, and so sound mixing.
If you're still interested in and have time, can you tell me if it fixes your issue?

**Comment by pvanthony** [comment]
> I created a pull request #5 to add an option which prevent multiple device connections, and so sound mixing. If you're still interested in and have time, can you tell me if it fixes your issue?

Wow!

Thank you very very very much for creating this patch. I will try it out and report back.

**Comment by pvanthony** [comment]
> @pvanthony Sorry for the late reply
> 
> I created a pull request #5 to add an option which prevent multiple device connections, and so sound mixing. If you're still interested in and have time, can you tell me if it fixes your issue?

Just tried it and it works great!!! Thank you for very much for adding this feature. Very useful. I will go and checkout the code you have done and try to understand and learn.

Once again thank you for sharing this project and adding this feature.
