### ISSUE TITLE
Bluetooth only works when SSH session is active

### ISSUE THREAD

**Issue by derhagen** [fdanis-oss/pw_wp_bluetooth_rpi_speaker#4]
See title. As soon as I `exit` the SSH session, the audio is gone. Raspberry Pi 4 B. I have set `Console Autologin` in `raspi-config`.

When trying to connect without being logged in to SSH, I get `Connection rejected by user` error messages

**Comment by ageorgios** [comment]
I have the same problem, it is because the service is enabled on user level
have you found a solution ?

**Comment by kiai72** [comment]
Hello,

i have a very similar problem
- bookwork + autologin
- my .bashrc ends like this:
    if [ "$SSH_CLIENT" ]; then
    echo skip myAutostart for SSH Sessions
  else
    echo myAutostart ...
    wpctl set-volume 60 1.0
    wpctl set-volume 61 1.0
    kodi &
  fi

only when i end kodi it works - OR: when i open a ssh session it also works. Seems like i have to have a command prompt running somewhere.

any idea how to fix this?
